export const demoProducts = [
  {
    id: "samsung-s24",
    brand: "Samsung",
    name: "Galaxy S24 Ultra (256GB)",
    category: "Electronics",
    priceCents: 2799900,
    discountPct: 10,
    rating: 4.7,
    stock: 12,
  },
  {
    id: "apple-iphone-16",
    brand: "Apple",
    name: "iPhone 16 Pro (256GB)",
    category: "Electronics",
    priceCents: 3399900,
    discountPct: 0,
    rating: 4.8,
    stock: 7,
  },
  {
    id: "nike-airmax",
    brand: "Nike",
    name: "Air Max 90 Sneakers",
    category: "Fashion",
    priceCents: 249990,
    discountPct: 15,
    rating: 4.4,
    stock: 25,
  },
  {
    id: "adidas-ultraboost",
    brand: "Adidas",
    name: "Ultraboost Running Shoes",
    category: "Fashion",
    priceCents: 299990,
    discountPct: 5,
    rating: 4.5,
    stock: 18,
  },
  {
    id: "dyson-v15",
    brand: "Dyson",
    name: "V15 Detect Cordless Vacuum",
    category: "Home",
    priceCents: 1599900,
    discountPct: 12,
    rating: 4.6,
    stock: 9,
  },
  {
    id: "sony-wh1000xm6",
    brand: "Sony",
    name: "WH-1000XM Noise Cancelling Headphones",
    category: "Electronics",
    priceCents: 899900,
    discountPct: 8,
    rating: 4.7,
    stock: 14,
  },
  {
    id: "lego-starwars",
    brand: "LEGO",
    name: "Star Wars Collector Set",
    category: "Toys",
    priceCents: 349990,
    discountPct: 0,
    rating: 4.9,
    stock: 6,
  },
  {
    id: "apple-airpods-pro",
    brand: "Apple",
    name: "AirPods Pro (2nd Gen)",
    category: "Electronics",
    priceCents: 599900,
    discountPct: 7,
    rating: 4.6,
    stock: 22,
  },
  {
    id: "smeg-kettle",
    brand: "Smeg",
    name: "Retro Electric Kettle",
    category: "Home",
    priceCents: 299900,
    discountPct: 18,
    rating: 4.3,
    stock: 10,
  },
  {
    id: "canon-eos",
    brand: "Canon",
    name: "EOS Mirrorless Camera Kit",
    category: "Electronics",
    priceCents: 2299900,
    discountPct: 6,
    rating: 4.5,
    stock: 5,
  },
  {
    id: "redbaton-hoodie",
    brand: "PONDO",
    name: "Streetwear Hoodie (Limited)",
    category: "Fashion",
    priceCents: 79990,
    discountPct: 20,
    rating: 4.2,
    stock: 30,
  },
  {
    id: "xbox-series",
    brand: "Microsoft",
    name: "Xbox Series Console",
    category: "Electronics",
    priceCents: 1299900,
    discountPct: 0,
    rating: 4.6,
    stock: 8,
  },
];

export function getCategories() {
  return [...new Set(demoProducts.map((p) => p.category))].sort();
}

export function findProduct(id) {
  return demoProducts.find((p) => p.id === id) || null;
}

