import type {
  AdminUser,
  CheckoutRecord,
  DriverAssignment,
  KpiMetric,
  KycAuditRecord,
  KycPieSlice,
  KycTrendPoint,
  PartnerPerformancePoint,
  RevenueTrendPoint,
  TxVolumePoint,
} from "@/types/admin";

export const adminUsers: AdminUser[] = [
  {
    id: "ADM-001",
    name: "Lebohang Mpeta",
    email: "lebo@pondo.co.za",
    role: "super_admin",
    avatar: "LM",
    subtitle: "Super Admin",
    permissions: ["system", "finance", "ops", "analytics"],
  },
  {
    id: "ADM-002",
    name: "Thabo Nkosi",
    email: "thabo@pondo.co.za",
    role: "operations_admin",
    avatar: "TN",
    subtitle: "Operations Admin",
    permissions: ["ops", "analytics", "drivers"],
  },
];

export const baseKpis: KpiMetric[] = [
  {
    id: "revenue",
    label: "Total Revenue Today",
    value: "R 1 332 148",
    hint: "+R14,280 last hr",
    accent: "#4e7dc8",
    surface: "#233863",
    icon: "REV",
  },
  {
    id: "completed",
    label: "Completed Checkouts",
    value: "1,847",
    hint: "+23 new this hour",
    accent: "#4e7dc8",
    surface: "#eef6ff",
    icon: "CHK",
  },
  {
    id: "clearance",
    label: "KYC Clearance Rate",
    value: "96.5%",
    hint: "12 pending review",
    accent: "#059669",
    surface: "#dff8e8",
    icon: "KYC",
  },
  {
    id: "drivers",
    label: "Active Drivers",
    value: "284",
    hint: "18 on-site delivery",
    accent: "#ad5f32",
    surface: "#fff2bf",
    icon: "DRV",
  },
  {
    id: "itc",
    label: "ITC Checks Today",
    value: "2,103",
    hint: "97.1% pass rate",
    accent: "#7c3aed",
    surface: "#efe7ff",
    icon: "ITC",
  },
  {
    id: "partners",
    label: "Fulfilment Partners",
    value: "5 Active",
    hint: "Amazon | Takealot | +3",
    accent: "#0891b2",
    surface: "#dbf4ff",
    icon: "FUL",
  },
  {
    id: "fraud",
    label: "Fraud Blocked",
    value: "3",
    hint: "0.002% fraud rate",
    accent: "#dc2626",
    surface: "#ffe2e2",
    icon: "FRD",
  },
  {
    id: "aov",
    label: "Avg Order Value",
    value: "R695",
    hint: "+R42 vs yesterday",
    accent: "#1f2f59",
    surface: "#f6f2ea",
    icon: "AOV",
  },
];

export const checkoutRecords: CheckoutRecord[] = [
  {
    id: "TXN-20260422-8821",
    consumer: "Sipho Dlamini",
    product: "iPhone 16 Pro 256GB",
    partner: "Amazon SA",
    amount: 26999,
    itc: "PASS",
    kyc: "PASS",
    vetting: "PASS",
    status: "COMPLETED",
    driver: "Mandla K.",
    time: "09:14",
  },
  {
    id: "TXN-20260422-8820",
    consumer: "Nomsa Khumalo",
    product: 'Samsung 65" QLED TV',
    partner: "Takealot",
    amount: 18999,
    itc: "PASS",
    kyc: "PASS",
    vetting: "PASS",
    status: "COMPLETED",
    driver: "Themi D.",
    time: "08:57",
  },
  {
    id: "TXN-20260422-8819",
    consumer: "James van der Berg",
    product: "MacBook Air M3",
    partner: "Amazon SA",
    amount: 32999,
    itc: "FAIL",
    kyc: "FAIL",
    vetting: "PENDING",
    status: "BLOCKED",
    driver: null,
    time: "08:44",
  },
  {
    id: "TXN-20260422-8818",
    consumer: "Aisha Mokoena",
    product: "Dyson V15",
    partner: "Takealot",
    amount: 12999,
    itc: "PASS",
    kyc: "PASS",
    vetting: "PASS",
    status: "IN_TRANSIT",
    driver: "Peter M.",
    time: "08:31",
  },
  {
    id: "TXN-20260422-8817",
    consumer: "Karabo Ndlovu",
    product: "PlayStation 5 Slim",
    partner: "Temu",
    amount: 15499,
    itc: "PASS",
    kyc: "REVIEW",
    vetting: "PENDING",
    status: "PENDING",
    driver: null,
    time: "08:12",
  },
];

export const kycAuditRecords: KycAuditRecord[] = [
  {
    ref: "KYC-8821",
    consumer: "Sipho Dlamini",
    saIdMasked: "9201145***082",
    itc: "PASS",
    kyc: "PASS",
    vetting: "PASS",
    status: "CLEARED",
    time: "09:14:22",
    product: "iPhone 16 Pro",
    amount: 26999,
  },
  {
    ref: "KYC-8820",
    consumer: "Nomsa Khumalo",
    saIdMasked: "8805228***034",
    itc: "PASS",
    kyc: "PASS",
    vetting: "PASS",
    status: "CLEARED",
    time: "08:57:11",
    product: 'Samsung 65" TV',
    amount: 18999,
  },
  {
    ref: "KYC-8819",
    consumer: "James van der Berg",
    saIdMasked: "9512034***067",
    itc: "FAIL",
    kyc: "PENDING",
    vetting: "PENDING",
    status: "BLOCKED",
    time: "08:44:03",
    product: "MacBook Air M3",
    amount: 32999,
  },
  {
    ref: "KYC-8818",
    consumer: "Aisha Mokoena",
    saIdMasked: "0003145***091",
    itc: "PASS",
    kyc: "PASS",
    vetting: "PASS",
    status: "CLEARED",
    time: "08:31:55",
    product: "Dyson V15",
    amount: 12999,
  },
  {
    ref: "KYC-8817",
    consumer: "Karabo Ndlovu",
    saIdMasked: "9709057***043",
    itc: "PASS",
    kyc: "REVIEW",
    vetting: "PENDING",
    status: "REVIEW",
    time: "08:12:19",
    product: "PlayStation 5 Slim",
    amount: 15499,
  },
];

export const driverAssignments: DriverAssignment[] = [
  {
    driverId: "DRV-084",
    name: "Mandla Khumalo",
    kycVerified: true,
    zone: "Sandton / Rosebank",
    status: "ACTIVE",
    currentAssignment: "TXN-8821 | iPhone 16 Pro",
    deliveriesToday: 14,
    rating: 4.9,
    pedDevice: "PED-A12",
    deliveryStep: "On-Site Verify",
  },
  {
    driverId: "DRV-071",
    name: "Themi Dlamini",
    kycVerified: true,
    zone: "Midrand / Centurion",
    status: "ACTIVE",
    currentAssignment: 'TXN-8820 | Samsung TV',
    deliveriesToday: 11,
    rating: 4.8,
    pedDevice: "PED-B07",
    deliveryStep: "Active Tracking",
  },
  {
    driverId: "DRV-063",
    name: "Peter Molefe",
    kycVerified: true,
    zone: "Soweto / Lenasia",
    status: "ACTIVE",
    currentAssignment: "TXN-8818 | Dyson V15",
    deliveriesToday: 9,
    rating: 4.7,
    pedDevice: "PED-C03",
    deliveryStep: "Driver Assigned",
  },
  {
    driverId: "DRV-091",
    name: "Lungelo Nkosi",
    kycVerified: true,
    zone: "Randburg / Fourways",
    status: "OFF_SHIFT",
    currentAssignment: null,
    deliveriesToday: 7,
    rating: 4.8,
    pedDevice: "PED-A09",
    deliveryStep: "Off Shift",
  },
];

export const txVolumeData: TxVolumePoint[] = [
  { hour: "06:00", completed: 40, failed: 3, pending: 6 },
  { hour: "07:00", completed: 120, failed: 4, pending: 8 },
  { hour: "08:00", completed: 240, failed: 6, pending: 12 },
  { hour: "09:00", completed: 310, failed: 5, pending: 10 },
  { hour: "10:00", completed: 280, failed: 7, pending: 15 },
  { hour: "11:00", completed: 400, failed: 9, pending: 18 },
  { hour: "12:00", completed: 450, failed: 13, pending: 26 },
  { hour: "13:00", completed: 370, failed: 10, pending: 16 },
];

export const kycTrendData: KycTrendPoint[] = [
  { day: "Mon", pass: 410, review: 22, fail: 13 },
  { day: "Tue", pass: 490, review: 18, fail: 10 },
  { day: "Wed", pass: 520, review: 28, fail: 16 },
  { day: "Thu", pass: 400, review: 20, fail: 11 },
  { day: "Fri", pass: 630, review: 24, fail: 9 },
  { day: "Sat", pass: 710, review: 31, fail: 12 },
  { day: "Sun", pass: 290, review: 8, fail: 5 },
];

export const revenueTrendData: RevenueTrendPoint[] = [
  { week: "W1 Apr", revenue: 820000, target: 760000 },
  { week: "W2 Apr", revenue: 1110000, target: 900000 },
  { week: "W3 Apr", revenue: 980000, target: 960000 },
  { week: "W4 Apr", revenue: 1260000, target: 1030000 },
];

export const kycPieData: KycPieSlice[] = [
  { name: "ITC Pass", value: 1847, color: "#34d399" },
  { name: "KYC Pass", value: 1823, color: "#4A7FA5" },
  { name: "Vetting Pass", value: 1801, color: "#1B2A4A" },
  { name: "Blocked", value: 43, color: "#ef4444" },
  { name: "Review", value: 84, color: "#f5b642" },
];

export const partnerPerformanceData: PartnerPerformancePoint[] = [
  { name: "Amazon SA", orders: 642, delivered: 621, success: 96.7 },
  { name: "Takealot", orders: 535, delivered: 519, success: 97.0 },
  { name: "Temu", orders: 287, delivered: 271, success: 94.4 },
  { name: "Shopify", orders: 197, delivered: 193, success: 98.0 },
  { name: "WooCommerce", orders: 186, delivered: 180, success: 96.8 },
];
