export type DemoCatalogProduct = {
  id: string;
  brand: string;
  name: string;
  category: string;
  priceCents: number;
  discountPct: number;
  rating: number;
  stock: number;
  merchantName: string;
  description: string;
  image: string;
};

export const DEMO_CATALOG: DemoCatalogProduct[] = [
  {
    id: "samsung-65-qled",
    brand: "Samsung",
    name: '65" QLED 4K Smart TV',
    category: "Electronics",
    priceCents: 1899900,
    discountPct: 24,
    rating: 4.7,
    stock: 14,
    merchantName: "TechHub SA",
    description: "Premium QLED television for trusted delivery and demo checkout flows.",
    image: "https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "samsung-s24",
    brand: "Samsung",
    name: "Galaxy S24 Ultra (256GB)",
    category: "Electronics",
    priceCents: 2799900,
    discountPct: 10,
    rating: 4.8,
    stock: 12,
    merchantName: "TechHub SA",
    description: "Flagship Samsung smartphone for elevated-verification checkout journeys.",
    image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "apple-iphone-16",
    brand: "Apple",
    name: "iPhone 16 Pro (256GB)",
    category: "Electronics",
    priceCents: 3399900,
    discountPct: 0,
    rating: 4.8,
    stock: 7,
    merchantName: "TechHub SA",
    description: "High-value Apple device used in risk scoring and premium device demos.",
    image: "https://images.unsplash.com/photo-1512499617640-c74ae3a79d37?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "sony-wh1000xm6",
    brand: "Sony",
    name: "WH-1000XM6 Noise Cancelling Headphones",
    category: "Electronics",
    priceCents: 899900,
    discountPct: 12,
    rating: 4.9,
    stock: 16,
    merchantName: "TechHub SA",
    description: "Premium over-ear headphones for trusted lifestyle commerce journeys.",
    image: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "apple-airpods-pro",
    brand: "Apple",
    name: "AirPods Pro (2nd Gen)",
    category: "Electronics",
    priceCents: 599900,
    discountPct: 8,
    rating: 4.7,
    stock: 20,
    merchantName: "TechHub SA",
    description: "Wireless audio companion item for upsell and accessory basket demos.",
    image: "https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "canon-eos-r10",
    brand: "Canon",
    name: "EOS R10 Mirrorless Camera Kit",
    category: "Electronics",
    priceCents: 2299900,
    discountPct: 6,
    rating: 4.6,
    stock: 9,
    merchantName: "TechHub SA",
    description: "Creator-focused camera bundle for mid-to-high value trusted delivery demos.",
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "xbox-series-x",
    brand: "Xbox",
    name: "Xbox Series X Console",
    category: "Electronics",
    priceCents: 1299900,
    discountPct: 9,
    rating: 4.8,
    stock: 11,
    merchantName: "TechHub SA",
    description: "High-demand console for gaming category growth and checkout demos.",
    image: "https://images.unsplash.com/photo-1621259182978-fbf93132d53d?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "dyson-v15",
    brand: "Dyson",
    name: "V15 Detect Cordless Vacuum",
    category: "Electronics",
    priceCents: 1599900,
    discountPct: 14,
    rating: 4.7,
    stock: 8,
    merchantName: "HomeTech SA",
    description: "Premium home tech appliance included for bigger-basket premium demos.",
    image: "https://images.unsplash.com/photo-1558317374-067fb5f30001?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "nike-airmax",
    brand: "Nike",
    name: "Air Max 90 Sneakers",
    category: "Fashion",
    priceCents: 249990,
    discountPct: 15,
    rating: 4.7,
    stock: 25,
    merchantName: "StyleHub SA",
    description: "Trusted footwear SKU used in lower-value basket and delivery demos.",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "adidas-ultraboost",
    brand: "Adidas",
    name: "Ultraboost Running Shoes",
    category: "Fashion",
    priceCents: 299990,
    discountPct: 5,
    rating: 4.6,
    stock: 18,
    merchantName: "StyleHub SA",
    description: "Performance fashion item for basket, settlement, and fulfilment demos.",
    image: "https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "redbaton-hoodie",
    brand: "Redbaton",
    name: "Oversized Fleece Hoodie",
    category: "Fashion",
    priceCents: 129990,
    discountPct: 18,
    rating: 4.5,
    stock: 30,
    merchantName: "StyleHub SA",
    description: "Comfort-led apparel item for affordable trusted-commerce baskets.",
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "levi-501",
    brand: "Levi's",
    name: "501 Original Fit Jeans",
    category: "Fashion",
    priceCents: 159990,
    discountPct: 10,
    rating: 4.6,
    stock: 22,
    merchantName: "StyleHub SA",
    description: "Classic denim staple for broader fashion browsing and cart-building.",
    image: "https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "puma-rsx",
    brand: "Puma",
    name: "RS-X Heritage Sneakers",
    category: "Fashion",
    priceCents: 219990,
    discountPct: 11,
    rating: 4.4,
    stock: 19,
    merchantName: "StyleHub SA",
    description: "Streetwear footwear option for variety in fashion-led conversion demos.",
    image: "https://images.unsplash.com/photo-1543508282-6319a3e2621f?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "converse-chuck-70",
    brand: "Converse",
    name: "Chuck 70 High Top",
    category: "Fashion",
    priceCents: 189990,
    discountPct: 7,
    rating: 4.5,
    stock: 15,
    merchantName: "StyleHub SA",
    description: "Timeless sneaker line for cross-category brand balance in the catalog.",
    image: "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "guess-denim-jacket",
    brand: "Guess",
    name: "Washed Denim Jacket",
    category: "Fashion",
    priceCents: 239990,
    discountPct: 9,
    rating: 4.3,
    stock: 13,
    merchantName: "StyleHub SA",
    description: "Layering piece for broader seasonal fashion merchandising.",
    image: "https://images.unsplash.com/photo-1523398002811-999ca8dec234?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "michael-kors-tote",
    brand: "Michael Kors",
    name: "Jet Set Leather Tote",
    category: "Fashion",
    priceCents: 449990,
    discountPct: 13,
    rating: 4.7,
    stock: 10,
    merchantName: "StyleHub SA",
    description: "Premium accessories item for higher-value fashion checkout paths.",
    image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=1200&q=80",
  },
];

export const IMAGE_BY_PRODUCT: Record<string, string> = Object.fromEntries(
  DEMO_CATALOG.map((product) => [product.id, product.image]),
);

export const FALLBACK_IMAGE =
  "https://images.unsplash.com/photo-1472851294608-062f824d29cc?auto=format&fit=crop&w=1200&q=80";

export const FALLBACK_PRODUCTS = DEMO_CATALOG.map((product) => ({
  id: product.id,
  brand: product.brand,
  name: product.name,
  category: product.category,
  priceCents: product.priceCents,
  discountPct: product.discountPct,
  rating: product.rating,
  stock: product.stock,
}));
